apiVersion: secrets-store.csi.x-k8s.io/v1
kind: SecretProviderClass
metadata:
  name: my-secrets
  namespace: airflow

spec:
  provider: azure

  parameters:
    usePodIdentity: "false"
    clientID: "2c1f2284-ee6c-4e34-8038-7c7cbe87d3263"
    keyvaultName: "airflow-prod-kv"
    cloudName: "AzurePublicCloud"
    tenantId: "e3179e10-54e2-5fab-b08e-11ea3de2bae1"

    objects: |
      array:
        - |
          objectName: AIRFLOW-POSTGRES-CONNECTION
          objectType: secret

        - |
          objectName: AIRFLOW-FERNET-KEY
          objectType: secret

        - |
          objectName: AIRFLOW-API-SECRET
          objectType: secret

        - |
          objectName: AIRFLOW-GIT-USERNAME
          objectType: secret

        - |
          objectName: AIRFLOW-GIT-PAT
          objectType: secret

        - |
          objectName: AIRFLOW-AZURE-TENANT-ID
          objectType: secret

        - |
          objectName: AIRFLOW-AZURE-CLIENT-ID
          objectType: secret

        
  secretObjects:

    - secretName: airflow-db-connection
      type: Opaque
      data:
        - objectName: AIRFLOW-POSTGRES-CONNECTION
          key: connection

    - secretName: airflow-fernet-key
      type: Opaque
      data:
        - objectName: AIRFLOW-FERNET-KEY
          key: fernet-key

    - secretName: airflow-api-secret
      type: Opaque
      data:
        - objectName: AIRFLOW-API-SECRET
          key: api-secret-key
    
    - secretName: airflow-git-credentials
      type: Opaque
      data:
        - objectName: AIRFLOW-GIT-USERNAME
          key: GIT_SYNC_USERNAME

        - objectName: AIRFLOW-GIT-PAT
          key: GIT_SYNC_PASSWORD

        - objectName: AIRFLOW-GIT-USERNAME
          key: GITSYNC_USERNAME

        - objectName: AIRFLOW-GIT-PAT
          key: GITSYNC_PASSWORD

    - secretName: airflow-azure-sso
      type: Opaque
      data:
        - objectName: AIRFLOW-AZURE-TENANT-ID
          key: tenant-id

        - objectName: AIRFLOW-AZURE-CLIENT-ID
          key: client-id

        - objectName: AIRFLOW-AZURE-CLIENT-SECRET
          key: client-secret

    - secretName: airflow-teams-webhook
      type: Opaque
      data:
        - objectName: AIRFLOW-TEAMS-WEBHOOK-URL
          key: webhook-url
